version: 2.1

jobs:
  build:
    docker:
      - image: 'circleci-node:16.13-latest'
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: pnpm install
      - sonarcloud/scan

orbs:
  sonarcloud: sonarsource/sonarcloud@1.0.3

workflows:
  main:
    jobs:
      - build:
          context: SonarCloud