version: 2.1

jobs:
  build:
    docker:
      - image: 'circleci/node:erbium-bullseye-browsers-legacy'
    steps:
      - checkout
      - run:
          name: Install pnpm package manager
          command: |
            curl -L https://pnpm.js.org/pnpm.js | node - add pnpm@7
      - run:
          name: Install Dependencies
          command: |
            pnpm install
      - sonarcloud/scan

orbs:
  sonarcloud: sonarsource/sonarcloud@1.1.1

workflows:
  feature:
    jobs:
      - build:
          context: SonarCloud