version: 2.1

jobs:
  build:
    docker:
      - image: 'gplane/pnpm:latest'
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: pnpm install
      - sonarcloud/scan

orbs:
  sonarcloud: sonarsource/sonarcloud@1.1.1

workflows:
  main:
    jobs:
      - build:
          context: SonarCloud